# Generated by Django 2.2.1 on 2019-05-30 14:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='callBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('clientPhone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('clientEmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('clientSite', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес сайта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий по клиенту')),
                ('is_done', models.BooleanField(default=False, verbose_name='Заявка отработана ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_descr', models.CharField(default='', max_length=150, verbose_name='Короткое описание')),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='showcases/', verbose_name='Картинка превью')),
                ('showcaseFullInfo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст новости')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название фотоальбома')),
                ('image', models.ImageField(upload_to='Albums/', verbose_name='Обложка альбома')),
                ('name_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фотоальбомы',
                'verbose_name_plural': 'Фотоальбом',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Photos/', verbose_name='Фотография')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.PhotoAlbum', verbose_name='В альбоме')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
