# Generated by Django 2.2.1 on 2019-05-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='show_at_homepage',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
    ]
